### ISSUE TITLE
Possible mistake at escaping ?

### ISSUE THREAD

**Issue by KarelGGIT** [philr/bzip2-windows#1]
Hi there,

i have a project with an external dependency that requires a library from bzip2... So i had to make it for visual studio 2015. Your repo is a godsend because the source code of the library contains old commands switches and other things that needs to be cleaned. However...

When i have downloaded your files, i have also modified `Build-Bzip2.ps1`, that

```
Param (
  [string]$GitPath = 'git',
  [string]$VisualStudioDir = 'C:\Program Files (x86)\Microsoft Visual Studio 12.0'  
)
```

Becomes

```
Param (
  [string]$GitPath = 'git',
  [string]$VisualStudioDir = 'C:\Program Files (x86)\Visual Studio 14.0'  
)
```

In the above folder, there is a subfolder "VC" which then contains `vcvarsall.bat`

```
PS C:\Program Files (x86)\Visual Studio 14.0\VC> Get-ChildItem -name
atlmfc
bin
crt
include
lib
Profile
redist
Snippets
UnitTest
VCAddClass
VCContextItems
VCNewItems
vcpackages
VCProjectDefaults
vcprojectitems
vcprojects
VCResourceTemplates
VCWizards
vcEmptyTestProject.vsz
vcvarsall.bat
```

see the last line. It is compliant with what you're doing when setting up a path:
`$VcVarsAllPath = Join-Path -Path (Join-Path -Path $VisualStudioDir -ChildPath 'VC') -ChildPath 'vcvarsall.bat'`

But, when running the script, I get an error. 

```
PS D:\downloads\temp\bzip2-windows-master> .\Build-Bzip2.ps1
Extracting archive
Applying patches
Applying patch 01-replace_deprecated_compile_options.diff
Applying patch 02-build_dll.diff
Applying patch 03-add_version_resource.diff
Applying patch 04-remove_unsupported_description_option.diff
Building x86
'""C:\Program' is not recognized as an internal or external command,
operable program or batch file.
Failed to build x86
At D:\downloads\temp\bzip2-windows-master\Build-Bzip2.ps1:100 char:13
+             throw "Failed to build $Architecture"
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : OperationStopped: (Failed to build x86:String) [], RuntimeException
    + FullyQualifiedErrorId : Failed to build x86
```

Apparently there could be some escaping issues, but the line that causes the error

```
cmd /C "`"`"$VcVarsAllPath`" $VcVars & nmake -f makefile.msc all`""
```

doesn't seem wrong. Well, if i could understand the mix of escapes... 
So I couldn't figure out the problem. I'm surprised that it has worked at you :P
Can you look into that ?

( in the meanwhile, i have used developer console to issue the nmake command on your patched files so that i have the dll. Many thanks for that)

**Comment by philr** [comment]
It looks like this is caused by either newer versions of PowerShell or newer versions of Windows.

I've just successfully run the script with PowerShell 3 on Windows 7 using both Visual Studio 2013 and 2015 to build.

However, I get an identical error when running with PowerShell 5 on Windows 10 using Visual Studio 2015.

**Comment by philr** [comment]
I've committed a change to remove an unnecessary level of argument quoting. The script now works with PowerShell 5 on Windows 10 as well as PowerShell 3 on Windows 7.

I've also updated the script to use Visual Studio 2015 by default.

Thank you for reporting this issue.
