### ISSUE TITLE
Executable cannot compress large files

### ISSUE THREAD

**Issue by Dobatymo** [philr/bzip2-windows#3]
Version: 1.0.6-win
Neither the x64 nor the x86 version managed to compress a 4.5 GB file.
```
bzip2: Input file large.file is not a normal file.
```

Small testfiles (few KB) worked.

**Comment by philr** [comment]
bzip2 uses the [`_stat`](https://docs.microsoft.com/cpp/c-runtime-library/reference/stat-functions) function on Windows to determine whether the file to compress exists. This will return an error if the file size is greater than 2<sup>32</sup> - 1 bytes, resulting in the 'not a normal file' output.

I've added a [patch](https://github.com/philr/bzip2-windows/blob/v1.0.6.1/patches/06-support_64bit_file_sizes.diff) to switch to `_stati64` instead. This variant of the `stat` function supports 64-bit file sizes.

I've built a new release ([v1.0.6.1](https://github.com/philr/bzip2-windows/releases/tag/v1.0.6.1)) that includes the patch.

**Comment by Dobatymo** [comment]
Thank you for this quick fix! I cannot believe that I am the first person to complain about this...
