### ISSUE TITLE
Bzip2 has a new official maintainer 

### ISSUE THREAD

**Issue by val-ms** [philr/bzip2-windows#4]
Julian Seward handed over maintainership of bzip2 to Federico Mena Quintero earlier this month: https://people.gnome.org/~federico/blog/maintaining-bzip2.html

Bzip2 finally has an official public repository, found here on gitlab: https://gitlab.com/federicomenaquintero/bzip2

Would you consider contributing your patches and version.rc file in a pull request to the new official repo?  I've been using them for my project for our Windows builds and they appear to work well for us.

**Comment by philr** [comment]
Thanks for the heads up. I'm happy to contribute everything back to the official project. I've opened [issue #17](https://gitlab.com/federicomenaquintero/bzip2/issues/17) to ask if they are interested.

**Comment by philr** [comment]
All the patches and the version.rc file from this project have now been merged in to the official repository (commits [636c0704](https://gitlab.com/federicomenaquintero/bzip2/commit/636c0704c7b245df7d1541aeab49f43b3cc6e866) and [6b9b943d](https://gitlab.com/federicomenaquintero/bzip2/commit/6b9b943d78ae7017a8de85537d6367a01d755c06)).

**Comment by val-ms** [comment]
Awesome.  Thanks Phil!

**Comment by sergeevabc** [comment]
Dear @philr,
Windows 7 x64 user here,
why did you choose to compile bzip2 as multiple files (exe+dll) rather than one (static)?

**Comment by philr** [comment]
@sergeevabc I was primarily interested in building libbz2.dll for use elsewhere.

The original makefile didn't build libbz2.dll. It statically links links libbz2 into bzip2.exe. This project [patches the makefile](https://github.com/philr/bzip2-windows/blob/8e56475016326118631e2d71d65e0067b877df9c/patches/02-build_dll.diff) to build libbz2.dll and link bzip2.exe to that.
